### ISSUE TITLE
getgraph parsing JSON failed

### ISSUE THREAD

**Issue by GearsAD** [glesica/Neo4j.jl#1]
Hi,

I'm new to Julia and Neo4j but was trying to get it to work on my local machine - it seems to have an issue when building the Neo4j graph after the JSON is retrieved. I updated Neo4j.jl to use the Request JSON parser and it seems to work now:
function getgraph(conn::Connection)
    resp = get(conn.url; headers=DEFAULT_HEADERS)
    if resp.status !== 200
        error("Connection to server unsuccessful: $(resp.status)")
    end
    Graph(**Requests.json(resp)**, conn)
end

Great code by the way, originally thought I had to write up an interface from scratch!

Thanks,
Sam

Details:
OS: Windows 7 x64
Versions:
- Neo4j: v3.0.1
- Julia: 0.4.5

**Comment by glesica** [comment]
Hey, I haven't maintained this for a couple years, so it is probably out of date. I also never finished it. I had originally intended to implement bindings for the full REST interface, but that interface really isn't terribly useful and most people seem to avoid it, preferring to simply use the Cypher endpoint to make queries directly. I've considered cleaning this up, so maybe I'll take a look at it and see what I can do with a reasonable level of effort.

**Comment by GearsAD** [comment]
Hi,

I forked it and made a few small changes to get it to run. I'm not fluent
in Julia at the moment, so I'm just brute-forcing it a bit, but it can be
found at https://github.com/GearsAD/Neo4j.jl. It only took a few small
changes to get it running again. Thanks again for putting it up!

**Comment by glesica** [comment]
@GearsAD I've got a branch that totally refactors the library to be a little friendlier and hopefully more useful: https://github.com/glesica/Neo4j.jl/pull/2 if you'd like to review it. Once I get that merged I'm going to submit it to the Julia package directory so it will be easy to install.

**Comment by glesica** [comment]
I've merged the updates so this issue no longer applies. Closing.
