### ISSUE TITLE
Any transaction returns 415 error

### ISSUE THREAD

**Issue by keorn** [glesica/Neo4j.jl#20]
```
HTTP.ExceptionRequest.StatusError(415, "POST", "/db/data/transaction", HTTP.Messages.Response:
"""
HTTP/1.1 415 Unsupported Media Type
Date: Sat, 11 Apr 2020 09:11:18 GMT
Access-Control-Allow-Origin: *
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 0

""")
```

**Comment by keorn** [comment]
`Content-Type` header field was missing. After fixing that I noticed some other differences from the current HTTP API, I guess the API was changed since this library was written?
Anyway, I wrote an MVP HTTP driver if that can be useful for fixing issues here: https://gitlab.com/plantingspace/neo4jbase.jl

**Comment by glesica** [comment]
I'm pretty sure most of the users are using private forks at this point. I'm not actively maintaining this repo at the moment, although I'm happy to merge pull requests that fix bugs.

**Comment by keorn** [comment]
Understood, why do you close this issue though if its legitimate?
