### ISSUE TITLE
Register Julia package

### ISSUE THREAD

**Issue by glesica** [glesica/Neo4j.jl#24]
@JuliaRegistrator register

**Comment by Affie** [comment]
Hi @glesica, did you install the registrator bot https://github.com/JuliaRegistries/Registrator.jl#install-registrator

**Comment by glesica** [comment]
@JuliaRegistrator register

**Comment by Affie** [comment]
Thanks, hopefully this (compat helper, registrator, tagbot) will make basic maintenance easier until we can update to an alternative driver.

**Comment by GearsAD** [comment]
Looks good, can close. Thanks @glesica!
